In [2]:
import os
project_name = "reco-tut-sjr"; branch = "main"; account = "sparsh-ai"
project_path = os.path.join('/content', project_name)

if not os.path.exists(project_path):
    !cp /content/drive/MyDrive/mykeys.py /content
    import mykeys
    !rm /content/mykeys.py
    path = "/content/" + project_name; 
    !mkdir "{path}"
    %cd "{path}"
    import sys; sys.path.append(path)
    !git config --global user.email "recotut@recohut.com"
    !git config --global user.name  "reco-tut"
    !git init
    !git remote add origin https://"{mykeys.git_token}":x-oauth-basic@github.com/"{account}"/"{project_name}".git
    !git pull origin "{branch}"
    !git checkout main
else:
    %cd "{project_path}"

/content/reco-tut-sjr
Initialized empty Git repository in /content/reco-tut-sjr/.git/
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 29 (delta 4), reused 25 (delta 1), pack-reused 0
Unpacking objects: 100% (29/29), done.
From https://github.com/sparsh-ai/reco-tut-sjr
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
Branch 'main' set up to track remote branch 'main' from 'origin'.
Switched to a new branch 'main'

In [59]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import NearestNeighbors
import spacy

In [55]:
# !python -m spacy download en_core_web_lg
!ls /usr/local/lib/python3.7/dist-packages/en_core_web_lg

en_core_web_lg-2.2.5  __init__.py  meta.json  __pycache__

In [56]:
nlp = spacy.load('/usr/local/lib/python3.7/dist-packages/en_core_web_lg/en_core_web_lg-2.2.5')

In [34]:
df_jobs = pd.read_pickle('./data/silver/jobs.p', compression='gzip')
df_jobs = df_jobs.reset_index(drop=True)
df_jobs.head()

   Job.ID  ...                                              Title
0   73666  ...              Cashiers & Valets Needed! @ WallyPark
1   96655  ...  Macy's Seasonal Retail Fragrance Cashier  - Ga...
2   84141  ...  Part Time Showroom Sales / Cashier @ Grizzly I...
3   77989  ...  Event Specialist Part Time @ Advantage Sales &...
4   69568  ...          Bonefish - Kitchen Staff @ Bonefish Grill

[5 rows x 3 columns]

In [35]:
df_users = pd.read_pickle('./data/silver/applicants.p', compression='gzip')
df_users = df_users.reset_index(drop=True)
df_users.head()

   Applicant_id                                             text
0             2                      volunteer writer uloop blog
1             3                   market intern server prep cook
2             6                                project assistant
3             8  deli clerk server cashier food prep order taker
4            11                                          cashier

## Selecting test user

In [37]:
def get_recommendation(top, df_all, scores):
  recommendation = pd.DataFrame(columns = ['ApplicantID', 'JobID',  'title', 'score'])
  count = 0
  for i in top:
      recommendation.at[count, 'ApplicantID'] = u
      recommendation.at[count, 'JobID'] = df_all['Job.ID'][i]
      recommendation.at[count, 'title'] = df_all['Title'][i]
      recommendation.at[count, 'score'] =  scores[count]
      count += 1
  return recommendation

In [38]:
u = 10001
index = np.where(df_users['Applicant_id'] == u)[0][0]
user_q = df_users.iloc[[index]]
user_q

      Applicant_id                                               text
6839         10001  part time showroom sales cashier grizzly indus...

## Model 1 - TFIDF

In [36]:
#initializing tfidf vectorizer
##This is a technique to quantify a word in documents, 
#we generally compute a weight to each word which signifies the importance of the word in the document and corpus. 
##This method is a widely used technique in Information Retrieval and Text Mining.
tfidf_vectorizer = TfidfVectorizer()

tfidf_jobid = tfidf_vectorizer.fit_transform((df_jobs['text'])) #fitting and transforming the vector
tfidf_jobid

<7047x6764 sparse matrix of type '<class 'numpy.float64'>'
	with 75495 stored elements in Compressed Sparse Row format>

Computing cosine similarity using tfidf

In [39]:
user_tfidf = tfidf_vectorizer.transform(user_q['text'])
cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf, x), tfidf_jobid)
output2 = list(cos_similarity_tfidf)

top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:10]
list_scores = [output2[i][0][0] for i in top]
get_recommendation(top, df_jobs, list_scores)

  ApplicantID  ...     score
0       10001  ...  0.611668
1       10001  ...  0.267901
2       10001  ...  0.255969
3       10001  ...  0.255373
4       10001  ...  0.243176
5       10001  ...  0.236469
6       10001  ...  0.232448
7       10001  ...  0.226873
8       10001  ...  0.226546
9       10001  ...  0.223953

[10 rows x 4 columns]

## Model 2 - CountVectorizer

In [41]:
count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform((df_jobs['text'])) #fitting and transforming the vector
count_jobid

<7047x6764 sparse matrix of type '<class 'numpy.int64'>'
	with 75495 stored elements in Compressed Sparse Row format>

In [43]:
user_count = count_vectorizer.transform(user_q['text'])
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output2 = list(cos_similarity_countv)

top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:10]
list_scores = [output2[i][0][0] for i in top]
get_recommendation(top, df_jobs, list_scores)

  ApplicantID  ...     score
0       10001  ...  0.683763
1       10001  ...  0.484182
2       10001  ...  0.484182
3       10001  ...   0.41574
4       10001  ...  0.408959
5       10001  ...  0.408959
6       10001  ...  0.408959
7       10001  ...  0.408959
8       10001  ...  0.408959
9       10001  ...  0.408959

[10 rows x 4 columns]

## Model 3 - Spacy

Transform the copurs text to the *spacy's documents*

In [ ]:
%%time
list_docs = []
for i in range(len(df_jobs)):
  doc = nlp("u'" + df_jobs['text'][i] + "'")
  list_docs.append((doc,i))
print(len(list_docs))

CPU times: user 33min 10s, sys: 18.7 s, total: 33min 28s
Wall time: 33min 29s

In [ ]:
def calculateSimWithSpaCy(nlp, df, user_text, n=6):
    # Calculate similarity using spaCy
    list_sim =[]
    doc1 = nlp("u'" + user_text + "'")
    for i in df.index:
      try:
            doc2 = list_docs[i][0]
            score = doc1.similarity(doc2)
            list_sim.append((doc1, doc2, list_docs[i][1],score))
      except:
        continue

    return  list_sim

In [ ]:
user_q.text[186]

'java developer'

In [ ]:
df3 = calculateSimWithSpaCy(nlp, df_jobs, user_q.text[186], n=15)
df_recom_spacy = pd.DataFrame(df3).sort_values([3], ascending=False).head(10)
df_recom_spacy.reset_index(inplace=True)

index_spacy = df_recom_spacy[2]
list_scores = df_recom_spacy[3]

CPU times: user 53 s, sys: 341 ms, total: 53.3 s
Wall time: 53 s

Top recommendations using Spacy

In [ ]:
get_recommendation(index_spacy, df_jobs, list_scores)

  ApplicantID   JobID                                         title     score
0         326  250216            Microstrategy Developer @ Kavaliro  0.698317
1         326  294489  Magento Developer (ONSITE) @ Creative Circle  0.654219
2         326  257251              Front End Developer @ ConsultNet      0.63
3         326  294684                     Java Developer @ Kavaliro  0.622253
4         326  257437    Drupal Developer-offsite @ Creative Circle  0.617237
5         326  316365      Jr. Ruby on Rails Developer @ ConsultNet  0.617211
6         326  257439    Drupal Developer-offsite @ Creative Circle  0.612062
7         326  257438    Drupal Developer-offsite @ Creative Circle  0.611012
8         326  257440    Drupal Developer-offsite @ Creative Circle  0.610952
9         326  303112                    Java Developer @ TransHire  0.610007

## Model 4 - KNN

In [60]:
n_neighbors = 11
KNN = NearestNeighbors(n_neighbors, p=2)
KNN.fit(tfidf_jobid)
NNs = KNN.kneighbors(user_tfidf, return_distance=True)

In [61]:
NNs[0][0][1:]

array([1.21004048, 1.21986152, 1.22035016, 1.23030395, 1.23574379,
       1.23899325, 1.24348464, 1.24374746, 1.24583083, 1.24791709])

The top recommendations using KNN

In [62]:
top = NNs[1][0][1:]
index_score = NNs[0][0][1:]

get_recommendation(top, df_jobs, index_score)

  ApplicantID   JobID                                       title    score
0       10001  174670                         Showroom Specialist  1.21004
1       10001  141536                     Account Manager - Sales  1.21986
2       10001  163435                     Account Manager - Sales  1.22035
3       10001  141080            Document Controller @ OfficeTeam   1.2303
4       10001  201340            Document Controller @ OfficeTeam  1.23574
5       10001   84946  Customer Service - Account Manager - Sales  1.23899
6       10001  163437  Customer Service - Account Manager - Sales  1.24348
7       10001  140866  Customer Service - Account Manager - Sales  1.24375
8       10001   84935  Customer Service - Account Manager - Sales  1.24583
9       10001  172424  Customer Service - Account Manager - Sales  1.24792